FLEXIBLE_ENGINE_ACCESS_KEY = "<Your FE Access key>"
FLEXIBLE_ENGINE_SECRET_KEY = "<Your FE Secret key>"
DOMAIN_NAME                = "<The targetted domain name>"
USERNAME                   = "<Your username>"
DOMAIN_ID                  = "<The targetted domain ID>"
