FLEXIBLE_ENGINE_ACCESS_KEY = "<Your FE Access key>"
FLEXIBLE_ENGINE_SECRET_KEY = "<Your FE Secret key>"
DOMAIN_NAME                = "<The targeted domain name>"
DOMAIN_ID                  = "<The targeted domain ID>"
USERNAME                   = "<Your username>"
